In [671]:
import pandas as pd
import re
df = pd.read_csv('Final-censusdataset-India.csv')  
print(df.head)

<bound method NDFrame.head of            state                                           District  persons  \
0        ANdaman  District Nicobars (01), Andaman & Nicobar Isla...   314084
1        ANdaman  District Nicobars (02), Andaman & Nicobar Isla...    42068
2         Andhra        District Adilabad (01), Andhra Pradesh (28)  2488003
3         Andhra       District Nizamabad (02), Andhra Pradesh (28)  2345685
4         Andhra      District Karimnagar (03), Andhra Pradesh (28)  3491822
..           ...                                                ...      ...
585  West Bengal           District Puruliya (14), West Bengal (19)  2536516
586  West Bengal                                 District Medinipur  9610788
587  West Bengal                                     District Haora  4273099
588  West Bengal            District Kolkata (17), West Bengal (19)  4572876
589  West Bengal        Twenty Four Parganas (18), West Bengal (19)  6906689

        Male   Female    rural  Person lit_rate  Male lit_Rate  \
0     170319   143765   197886            82.49          87.36
1      22653    19415    42068            72.35          78.55
2    1250958  1237045  1827986            52.68          64.98
3    1162905  1182780  1920947            52.02          64.91
4    1747968  1743854  2813010            54.90          67.09
..       ...      ...      ...              ...            ...
585  1298078  1238438  2281090            55.57          73.72
586  4916370  4694418  8626883            74.90          84.91
587  2241898  2031201  2121109            77.01          83.22
588  2500040  2072836        -            80.86          83.79
589  3564993  3341696  5820469            69.45          79.19

     Female lit_Rate  Tempworkers  ...  religion1 population     Religion2  \
0              76.62       166631  ...                235862  2.Christians
1              65.01        19623  ...                 28145      2.Hindus
2              40.30      1423248  ...               2207843           NaN
3              39.48      1159606  ...               1983275     2.Muslims
4              42.75      1711559  ...               3251834     2.Muslims
..               ...          ...  ...                   ...           ...
585            36.50      1127488  ...               2116037      2.Others
586            64.42      3751057  ...               8224779     2.Muslims
587            70.11      1438874  ...               3204077     2.Muslims
588            77.30      1717734  ...               3552274     2.Muslims
589            59.01      2242760  ...               4548459           NaN

     Religion2 Population     Religion3  religion3 Population  \
0                   49033     3.Muslims                 27134
1                   10727     3.Muslims                  2131
2                  236844           NaN                 24392
3                  338824  3.Christians                 16204
4                  213811  3.Christians                 20576
..                    ...           ...                   ...
585                226912     3.Muslims                180694
586               1088618      3.Others                262578
587               1044383       3.Jains                  9585
588                926769  3.Christians                 40218
589               2295967           NaN                 52835

    inhabitadevillages  drinkingwater electricity  primary school  \
0                331.0          331.0       233.0           185.0
1                170.0          169.0        96.0            53.0
2               1586.0         1585.0      1585.0          1521.0
3                854.0          854.0       854.0           839.0
4               1047.0         1047.0      1047.0          1039.0
..                 ...            ...         ...             ...
585             2468.0         2452.0      1232.0          2135.0
586            10548.0        10475.0      4835.0          6133.0
587              727.0          726.0       682.0           683.0
588                NaN            NaN         NaN             NaN
589             2087.0         2079.0      1322.0          1774.0

     Medical facility
0                 102
1                  38
2                 976
3                 614
4                 863
..                ...
585              1173
586              3560
587               410
588               NaN
589              1311

[590 rows x 24 columns]>

In [672]:
def clean_district_name(district_name):
    cleaned_name = district_name.replace("District ", "")
    cleaned_name = re.sub(r"\(\d+\), .* \(\d+\)", "", cleaned_name).strip() # Removing pattern "(xx), state (yy)" 
    return cleaned_name

df['District'] = df['District'].apply(clean_district_name)
df.to_csv('cleaned_dataset.csv', index=False)

In [673]:
df1 = pd.read_csv('cleaned_dataset.csv')  
print(df.head)

<bound method NDFrame.head of            state              District  persons     Male   Female    rural  \
0        ANdaman              Nicobars   314084   170319   143765   197886
1        ANdaman              Nicobars    42068    22653    19415    42068
2         Andhra              Adilabad  2488003  1250958  1237045  1827986
3         Andhra             Nizamabad  2345685  1162905  1182780  1920947
4         Andhra            Karimnagar  3491822  1747968  1743854  2813010
..           ...                   ...      ...      ...      ...      ...
585  West Bengal              Puruliya  2536516  1298078  1238438  2281090
586  West Bengal             Medinipur  9610788  4916370  4694418  8626883
587  West Bengal                 Haora  4273099  2241898  2031201  2121109
588  West Bengal               Kolkata  4572876  2500040  2072836        -
589  West Bengal  Twenty Four Parganas  6906689  3564993  3341696  5820469

     Person lit_rate  Male lit_Rate  Female lit_Rate  Tempworkers  ...  \
0              82.49          87.36            76.62       166631  ...
1              72.35          78.55            65.01        19623  ...
2              52.68          64.98            40.30      1423248  ...
3              52.02          64.91            39.48      1159606  ...
4              54.90          67.09            42.75      1711559  ...
..               ...            ...              ...          ...  ...
585            55.57          73.72            36.50      1127488  ...
586            74.90          84.91            64.42      3751057  ...
587            77.01          83.22            70.11      1438874  ...
588            80.86          83.79            77.30      1717734  ...
589            69.45          79.19            59.01      2242760  ...

     religion1 population     Religion2  Religion2 Population     Religion3  \
0                  235862  2.Christians                 49033     3.Muslims
1                   28145      2.Hindus                 10727     3.Muslims
2                 2207843           NaN                236844           NaN
3                 1983275     2.Muslims                338824  3.Christians
4                 3251834     2.Muslims                213811  3.Christians
..                    ...           ...                   ...           ...
585               2116037      2.Others                226912     3.Muslims
586               8224779     2.Muslims               1088618      3.Others
587               3204077     2.Muslims               1044383       3.Jains
588               3552274     2.Muslims                926769  3.Christians
589               4548459           NaN               2295967           NaN

     religion3 Population inhabitadevillages  drinkingwater electricity  \
0                   27134              331.0          331.0       233.0
1                    2131              170.0          169.0        96.0
2                   24392             1586.0         1585.0      1585.0
3                   16204              854.0          854.0       854.0
4                   20576             1047.0         1047.0      1047.0
..                    ...                ...            ...         ...
585                180694             2468.0         2452.0      1232.0
586                262578            10548.0        10475.0      4835.0
587                  9585              727.0          726.0       682.0
588                 40218                NaN            NaN         NaN
589                 52835             2087.0         2079.0      1322.0

     primary school  Medical facility
0             185.0               102
1              53.0                38
2            1521.0               976
3             839.0               614
4            1039.0               863
..              ...               ...
585          2135.0              1173
586          6133.0              3560
587           683.0               410
588             NaN               NaN
589          1774.0              1311

[590 rows x 24 columns]>

In [674]:
df2 = pd.read_csv('women-crimedataset-India (2).csv')  
print(df.head)

<bound method NDFrame.head of            state              District  persons     Male   Female    rural  \
0        ANdaman              Nicobars   314084   170319   143765   197886
1        ANdaman              Nicobars    42068    22653    19415    42068
2         Andhra              Adilabad  2488003  1250958  1237045  1827986
3         Andhra             Nizamabad  2345685  1162905  1182780  1920947
4         Andhra            Karimnagar  3491822  1747968  1743854  2813010
..           ...                   ...      ...      ...      ...      ...
585  West Bengal              Puruliya  2536516  1298078  1238438  2281090
586  West Bengal             Medinipur  9610788  4916370  4694418  8626883
587  West Bengal                 Haora  4273099  2241898  2031201  2121109
588  West Bengal               Kolkata  4572876  2500040  2072836        -
589  West Bengal  Twenty Four Parganas  6906689  3564993  3341696  5820469

     Person lit_rate  Male lit_Rate  Female lit_Rate  Tempworkers  ...  \
0              82.49          87.36            76.62       166631  ...
1              72.35          78.55            65.01        19623  ...
2              52.68          64.98            40.30      1423248  ...
3              52.02          64.91            39.48      1159606  ...
4              54.90          67.09            42.75      1711559  ...
..               ...            ...              ...          ...  ...
585            55.57          73.72            36.50      1127488  ...
586            74.90          84.91            64.42      3751057  ...
587            77.01          83.22            70.11      1438874  ...
588            80.86          83.79            77.30      1717734  ...
589            69.45          79.19            59.01      2242760  ...

     religion1 population     Religion2  Religion2 Population     Religion3  \
0                  235862  2.Christians                 49033     3.Muslims
1                   28145      2.Hindus                 10727     3.Muslims
2                 2207843           NaN                236844           NaN
3                 1983275     2.Muslims                338824  3.Christians
4                 3251834     2.Muslims                213811  3.Christians
..                    ...           ...                   ...           ...
585               2116037      2.Others                226912     3.Muslims
586               8224779     2.Muslims               1088618      3.Others
587               3204077     2.Muslims               1044383       3.Jains
588               3552274     2.Muslims                926769  3.Christians
589               4548459           NaN               2295967           NaN

     religion3 Population inhabitadevillages  drinkingwater electricity  \
0                   27134              331.0          331.0       233.0
1                    2131              170.0          169.0        96.0
2                   24392             1586.0         1585.0      1585.0
3                   16204              854.0          854.0       854.0
4                   20576             1047.0         1047.0      1047.0
..                    ...                ...            ...         ...
585                180694             2468.0         2452.0      1232.0
586                262578            10548.0        10475.0      4835.0
587                  9585              727.0          726.0       682.0
588                 40218                NaN            NaN         NaN
589                 52835             2087.0         2079.0      1322.0

     primary school  Medical facility
0             185.0               102
1              53.0                38
2            1521.0               976
3             839.0               614
4            1039.0               863
..              ...               ...
585          2135.0              1173
586          6133.0              3560
587           683.0               410
588             NaN               NaN
589          1774.0              1311

[590 rows x 24 columns]>

In [675]:
df1['District'] = df1['District'].str.strip().str.lower()
df2['District'] = df2['District'].str.strip().str.lower()

In [676]:
merged_df = pd.merge(df2, df1, left_on='District', right_on='District', how='inner')

In [677]:
merged_df.head()

,state_x,District,YEAR,MURDER,ATTEMPT TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS,...,religion1 population,Religion2,Religion2 Population,Religion3,religion3 Population,inhabitadevillages,drinkingwater,electricity,primary school,Medical facility
0,ANDHRA PRADESH,adilabad,2001.0,101,60,50,0,50,46,30,...,2207843,NaN,236844,NaN,24392,1586.0,1585.0,1585.0,1521.0,976
1,ANDHRA PRADESH,adilabad,2002.0,100,79,37,0,37,42,32,...,2207843,NaN,236844,NaN,24392,1586.0,1585.0,1585.0,1521.0,976
2,ANDHRA PRADESH,adilabad,2003.0,107,65,35,0,35,46,16,...,2207843,NaN,236844,NaN,24392,1586.0,1585.0,1585.0,1521.0,976
3,ANDHRA PRADESH,adilabad,2004.0,113,83,50,0,50,48,42,...,2207843,NaN,236844,NaN,24392,1586.0,1585.0,1585.0,1521.0,976
4,ANDHRA PRADESH,adilabad,2005.0,108,48,53,0,53,65,46,...,2207843,NaN,236844,NaN,24392,1586.0,1585.0,1585.0,1521.0,976

In [678]:
merged_df.to_csv('merged_dataset.csv', index=False)

In [679]:

#merged_df_unique = merged_df.drop_duplicates(subset=['District'], keep='first')

#merged_df_unique

In [680]:
#merged_df_unique.to_csv('merged_dataset.csv', index=False)

In [681]:
merged_df = merged_df.sort_values(by=['state_x', 'District', 'YEAR'])

merged_df = merged_df.reset_index(drop=True)
merged_df.head()

,state_x,District,YEAR,MURDER,ATTEMPT TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS,...,religion1 population,Religion2,Religion2 Population,Religion3,religion3 Population,inhabitadevillages,drinkingwater,electricity,primary school,Medical facility
0,A & N ISLANDS,north,2012.0,5,0,4,0,4,0,0,...,609493,2.Muslims,126093,3.Sikhs,20819,5.0,5.0,4.0,3.0,3
1,A & N ISLANDS,north,2012.0,5,0,4,0,4,0,0,...,22603,2.Hindus,16128,3.Christians,1623,53.0,53.0,46.0,42.0,44
2,A & N ISLANDS,south,2012.0,8,3,8,0,8,7,6,...,1824645,2.Muslims,314015,3.Sikhs,75102,16.0,16.0,16.0,12.0,7
3,A & N ISLANDS,south,2012.0,8,3,8,0,8,7,6,...,84213,2.Buddhists,31109,3.Christians,12757,145.0,145.0,142.0,131.0,99
4,ANDHRA PRADESH,adilabad,2001.0,101,60,50,0,50,46,30,...,2207843,NaN,236844,NaN,24392,1586.0,1585.0,1585.0,1521.0,976

In [682]:
merged_df.rename(columns={'state_x': 'state'}, inplace=True)
merged_df.drop(columns=['state_y'], inplace=True)

print(merged_df)
merged_df.to_csv('merged_dataset.csv', index=False)

               state        District    YEAR MURDER ATTEMPT TO MURDER RAPE  \
0      A & N ISLANDS           north  2012.0      5                 0    4
1      A & N ISLANDS           north  2012.0      5                 0    4
2      A & N ISLANDS           south  2012.0      8                 3    8
3      A & N ISLANDS           south  2012.0      8                 3    8
4     ANDHRA PRADESH        adilabad  2001.0    101                60   50
...              ...             ...     ...    ...               ...  ...
6673     WEST BENGAL  uttar dinajpur  2010.0     63               106  130
6674     WEST BENGAL  uttar dinajpur  2011.0     66               178  126
6675     WEST BENGAL  uttar dinajpur  2012.0    110               283   92
6676     WEST BENGAL  uttar dinajpur  2015.0    NaN                86   50
6677     WEST BENGAL  uttar dinajpur  2019.0      0                39   42

     CUSTODIAL RAPE OTHER RAPE KIDNAPPING & ABDUCTION  \
0                 0          4                      0
1                 0          4                      0
2                 0          8                      7
3                 0          8                      7
4                 0         50                     46
...             ...        ...                    ...
6673              0        130                    118
6674              0        126                    172
6675              0         92                    306
6676              0        NaN                      1
6677              0          0                     29

     KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS  ... religion1 population  \
0                                              0  ...               609493
1                                              0  ...                22603
2                                              6  ...              1824645
3                                              6  ...                84213
4                                             30  ...              2207843
...                                          ...  ...                  ...
6673                                          99  ...              1263001
6674                                         149  ...              1263001
6675                                         258  ...              1263001
6676                                          72  ...              1263001
6677                                         153  ...              1263001

        Religion2 Religion2 Population     Religion3 religion3 Population  \
0       2.Muslims               126093       3.Sikhs                20819
1        2.Hindus                16128  3.Christians                 1623
2       2.Muslims               314015       3.Sikhs                75102
3     2.Buddhists                31109  3.Christians                12757
4             NaN               236844           NaN                24392
...           ...                  ...           ...                  ...
6673    2.Muslims              1156503  3.Christians                13172
6674    2.Muslims              1156503  3.Christians                13172
6675    2.Muslims              1156503  3.Christians                13172
6676    2.Muslims              1156503  3.Christians                13172
6677    2.Muslims              1156503  3.Christians                13172

     inhabitadevillages  drinkingwater  electricity  primary school  \
0                   5.0            5.0          4.0             3.0
1                  53.0           53.0         46.0            42.0
2                  16.0           16.0         16.0            12.0
3                 145.0          145.0        142.0           131.0
4                1586.0         1585.0       1585.0          1521.0
...                 ...            ...          ...             ...
6673             1477.0         1465.0        757.0          1044.0
6674             1477.0         1465.0        757.0          1044.0
6675             1477.0         1465.0        757.0          1044.0
6676             1477.0         1465.0        757.0          1044.0
6677             1477.0         1465.0        757.0          1044.0

     Medical facility
0                   3
1                  44
2                   7
3                  99
4                 976
...               ...
6673              648
6674              648
6675              648
6676              648
6677              648

[6678 rows x 38 columns]

In [683]:
merged_df['Religion1'] = merged_df['Religion1'].str.split('.').str[1].str.strip()
merged_df['Religion2'] = merged_df['Religion2'].str.split('.').str[1].str.strip()
merged_df['Religion3'] = merged_df['Religion3'].str.split('.').str[1].str.strip()

# View the modified DataFrame
print(merged_df)

               state        District    YEAR MURDER ATTEMPT TO MURDER RAPE  \
0      A & N ISLANDS           north  2012.0      5                 0    4
1      A & N ISLANDS           north  2012.0      5                 0    4
2      A & N ISLANDS           south  2012.0      8                 3    8
3      A & N ISLANDS           south  2012.0      8                 3    8
4     ANDHRA PRADESH        adilabad  2001.0    101                60   50
...              ...             ...     ...    ...               ...  ...
6673     WEST BENGAL  uttar dinajpur  2010.0     63               106  130
6674     WEST BENGAL  uttar dinajpur  2011.0     66               178  126
6675     WEST BENGAL  uttar dinajpur  2012.0    110               283   92
6676     WEST BENGAL  uttar dinajpur  2015.0    NaN                86   50
6677     WEST BENGAL  uttar dinajpur  2019.0      0                39   42

     CUSTODIAL RAPE OTHER RAPE KIDNAPPING & ABDUCTION  \
0                 0          4                      0
1                 0          4                      0
2                 0          8                      7
3                 0          8                      7
4                 0         50                     46
...             ...        ...                    ...
6673              0        130                    118
6674              0        126                    172
6675              0         92                    306
6676              0        NaN                      1
6677              0          0                     29

     KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS  ... religion1 population  \
0                                              0  ...               609493
1                                              0  ...                22603
2                                              6  ...              1824645
3                                              6  ...                84213
4                                             30  ...              2207843
...                                          ...  ...                  ...
6673                                          99  ...              1263001
6674                                         149  ...              1263001
6675                                         258  ...              1263001
6676                                          72  ...              1263001
6677                                         153  ...              1263001

      Religion2 Religion2 Population   Religion3 religion3 Population  \
0       Muslims               126093       Sikhs                20819
1        Hindus                16128  Christians                 1623
2       Muslims               314015       Sikhs                75102
3     Buddhists                31109  Christians                12757
4           NaN               236844         NaN                24392
...         ...                  ...         ...                  ...
6673    Muslims              1156503  Christians                13172
6674    Muslims              1156503  Christians                13172
6675    Muslims              1156503  Christians                13172
6676    Muslims              1156503  Christians                13172
6677    Muslims              1156503  Christians                13172

     inhabitadevillages  drinkingwater  electricity  primary school  \
0                   5.0            5.0          4.0             3.0
1                  53.0           53.0         46.0            42.0
2                  16.0           16.0         16.0            12.0
3                 145.0          145.0        142.0           131.0
4                1586.0         1585.0       1585.0          1521.0
...                 ...            ...          ...             ...
6673             1477.0         1465.0        757.0          1044.0
6674             1477.0         1465.0        757.0          1044.0
6675             1477.0         1465.0        757.0          1044.0
6676             1477.0         1465.0        757.0          1044.0
6677             1477.0         1465.0        757.0          1044.0

     Medical facility
0                   3
1                  44
2                   7
3                  99
4                 976
...               ...
6673              648
6674              648
6675              648
6676              648
6677              648

[6678 rows x 38 columns]

In [684]:
print(merged_df.columns)

Index(['state', 'District', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER', 'RAPE',
       'CUSTODIAL RAPE', 'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS',
       'KIDNAPPING AND ABDUCTION OF OTHERS', 'DOWRY DEATHS',
       'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES', 'persons', 'Male',
       'Female', 'rural', 'Person lit_rate', 'Male lit_Rate',
       'Female lit_Rate', 'Tempworkers', 'Mainworkers', 'Marginal workers',
       'Nonworkers', 'Religion1', 'religion1 population', 'Religion2',
       'Religion2 Population', 'Religion3', 'religion3 Population',
       'inhabitadevillages', 'drinkingwater', 'electricity', 'primary school',
       'Medical facility'],
      dtype='object')

For the purpose of this study, while analysing crime patterns against women in India, we will look at the recent census parameters: such as literacy rate (overall, male literacy, female literacy
'Total Population'
'Male Population',
'Female Population', 
'rural', 
'urban', 
'Personlit_rate',
'Mlit_Rate', 
'Flit_Rate', 
'Totalworkers',
'Mainworkers', 
'Marginal workers', 
'Nonworkers', 
'Religion1',
'religion1 population', 'Religion2', 'Religion2 Population',



and other irrelevant columns for the purpose of this study ie 'inhabitadevillages', 'drinkingwater', 'electricity', 'primary school', 'Medical facility', we will drop from the dataset

In [686]:
# Dropping irrelevant columns
irrelevant_columns = ['inhabitadevillages', 'drinkingwater', 'electricity', 'primary school', 'Medical facility']
merged_df = merged_df.drop(columns=irrelevant_columns)

# Calculating unemployment rate
merged_df['unemployment_rate'] = (merged_df['Nonworkers'] / (merged_df['Tempworkers'] + merged_df['Mainworkers'] + merged_df['Marginal workers'])) * 100

# Calculating urban population
merged_df['persons'] = pd.to_numeric(merged_df['persons'], errors='coerce')
merged_df['rural'] = pd.to_numeric(merged_df['rural'], errors='coerce')
merged_df['urban_population'] = merged_df['persons'] - merged_df['rural']

# Rename 'rural' column to 'rural population'
merged_df.rename(columns={'rural': 'rural_population'}, inplace=True)

# View the modified DataFrame
print(merged_df)

KeyError: "['inhabitadevillages', 'drinkingwater', 'electricity', 'primary school', 'Medical facility'] not found in axis"

In [ ]:

merged_df.to_csv('merged_dataset.csv', index=False)